"""update teachers table

Revision ID: 70616b93677e
Revises: ea8175eeff29
Create Date: 2026-07-01 00:43:40.921077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70616b93677e'
down_revision: Union[str, Sequence[str], None] = 'ea8175eeff29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('address', sa.Text(), nullable=True))
    op.drop_column('teachers', 'frist_name')
    op.drop_column('teachers', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('adress', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('frist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'first_name')
    # ### end Alembic commands ###
