"""initial migration

Revision ID: ea8175eeff29
Revises: 
Create Date: 2026-06-30 23:44:30.942894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8175eeff29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('roll_number', sa.String(), nullable=True))
    op.add_column('students', sa.Column('address', sa.Text(), nullable=True))
    op.drop_column('students', 'adress')
    op.drop_column('students', 'roll_num')
    op.drop_column('students', 'frist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('frist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('roll_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('adress', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('students', 'address')
    op.drop_column('students', 'roll_number')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
